### ISSUE TITLE
type in the setup section in readMe

### ISSUE THREAD

**Issue by kaoussi** [cklmercer/vue-stack-2.0#1]
You have a typo in the setup section in readMe!
git clone https://github.com/cklmerver/vue-stack-2.0 should be
git clone https://github.com/cklmercer/vue-stack-2.0 !
I know it's a simple thing, but I've been asking what's wrong all the time, but at the end it's just a typo xD 
thanks for this boilerplate anyway

**Comment by cklmercer** [comment]
Thanks for the heads up. I'll get this fixed.
